# -*- coding: utf-8 -*-
"""Assignment/Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sMkX0iSa-KcxhP92nInnsGyqLQokVBoV

#1) Is a list mutable?
**Answer:** Yes, lists are mutable.
"""

list = [1,2,3,4,5]
list[0] = 'Mary'
print(list)

"""# 2) Does a list need to be homogeneous? 
**Answer:** List can contain heterogeneous values such as integers, floats, strings, tuples, lists, and dictionaries.

"""

list = [1,'Mary',5.5,{'number':1200}]
print(list)

"""# 3) What is the difference between a list and a tuple.
**Answer:**  [Lists] are mutable, while (tuples) are immutable.
"""

# Example of a mutable list:
list = [1,2,3,4,5]
list[2] = 'Two'
print(list)
# Example of an immutable tuple:
tuple = (1,'Two',3.0,[4])
print(tuple)
#tuple['Two'] = 2

"""# 4) How to find the number of elements in the list? 
**Answer:** With len() function.

"""

list = [1,2,3]
print(len(list))

"""# 5) How to check whether the list is empty or not?

"""

a =[]
if not a:
  print("List is empty")

"""6) How to find the first and last element of the list?
**Answer:** With indexing and reverse indexing

"""

list = [1,2,3,4,5]
# To find the first element of the list:
a= list[0]
print('the first element is :',a)
# To find the last element of the list:
b= list[-1]
print('the last element is :',b)

"""# 7) How to find the largest and lowest value in the list?
**Answer:** min() and max() function.

"""

list = [1,2,3,4,5,6,7,8,9,10]
print(min(list))
print(max(list))

"""# 8) How to access elements of the list?
**Answer:** By giving the index of the element in 1D array or loc() and iloc() function for dataframe.

"""

# Example of 1D array
list = [1,2,3,4,5]
print(list[3])
print(list[0:4])
# Example of Dataframe
import pandas as pd
list = [1,2,3,4,5,6,7,8,9]
df=pd.DataFrame(list)
a = df.iloc[:3]
print(a)

"""# 9) Remove elements in a list before a specific index


"""

list = [1,2,3,4,5,6,7,8,9]
print(list)

#Example of pop function
list.pop(0)
print(list)

#Example of Remove function
list.remove(2)
print(list)

#Example of delete function
del list[0]
print(list)

"""#10) Remove elements in a list between 2 indices"""



"""# 11) Return every 2nd element in a list between 2 indices


"""

a = [1,2,3,4,5,6,7,8,9]
del a[::2]
print(a)

"""# 12) Get the first element from each nested list in a list

# 13) How to modify elements of the list?
"""

list =[1,2,3,5]
list[3]=4
print(list)

"""#14) How to concatenate two lists?
**Answer:** By using extend() function
"""

a=[1,2,3]
b=[4,5,6]
a.extend(b)
print(a)

"""# 15) How to add two lists element-wise in python?
**Answer:** By using append() function

"""

a=[1,2,3]
b=[4,5,6]
a.append(b)
print(a)

"""# 16) Difference between del and clear?
**Answer:** Del will delete the elements while clear will clear the whole list.
"""

list= [1, 2, 3,4,5,6]
print (list)

# Example of Delete 
del list[0]
print(list)

# Example of clear
list.clear()
print(list)

"""# 17) Difference between remove and pop?
**Answer:** Remove() will remove the object while, pop will remove the element by it's index.

"""

list = [1,2,3,4,5,6,7,8,9]
print(list)

#Example of pop function
list.pop(0)
print(list)

#Example of Remove function
list1 = [1,2,3,4,5,6,7,8,9]
print(list1)
list1.remove(2)
print(list1)

"""# 18) Difference between append and extend?
**Answer:** append() method adds an element to a list, and the extend() method concatenates the first list with another list (or another iterable).
"""

a=[1,2,3]
b=[4,5,6]
a.extend(b)
print(a)
a.append(b)
print(a)

"""# 19) Difference between indexing and Slicing?
**Answer:** index will give us the index of specified value, while slicing will give value or group of values of specified index.

## 20) Difference between sort and sortted?
**Answer:** The sort() function will modify
the list it is called on. The sorted() function will create a 
new list containing a sorted version of the list it is given.
"""

#Example of sort 
a = [1,8,2,7,3,6,9,4,5]
a.sort()
print(a)

#Example of sortted
a = [1,8,2,7,3,6,9,4,5]
print(sorted(a))
print(a)

"""# 21) Difference between reverse and reversed?
**Answer:** reverse() actually reverses the elements in the container. reversed() doesn't actually reverse anything, it merely returns an object that can be used to iterate over the container's elements in reverse order.

## 22) Difference between copy and deep copy?

# 23) How to remove duplicate elements in the list?
"""

dup = [2, 4, 10, 20, 5, 2, 20, 4]
print(dup)
Removed = sorted(set(dup))
print(Removed)

"""# 24) How to find an index of an element in the python list?


"""

a = [1,8,2,7,3,6,9,4,5]
a.index(3)

"""# 25) How to find the occurrences of an element in the python list?
**Answer:** By using count() function.

"""

a = [1,2,2,7,3,2,6,9,2,4,5]
b = a.count(2)
print(b)

"""# 26) How to insert an item at a given position?
**Answer:** By using insery function and the item index.
"""

list =[1,2,4,5]
list.insert(2,3)
print(list)

"""# 27) How to check if an item is in the list?

**Answer:** By using "is in" method if it return True then The element was in list otherwise false.
"""

list = [1,2,3,4,5]
if 6 in list:
  print('False')
else:
  print('True')

"""# 28) How to flatten a list in python?"""

a = [[1,2],[3,4]]
print (a)
# flat_list = [item for sublist in t for item in sublist]
flatten = lambda t: [item for sublist in t for item in sublist]
print (flatten)